name: First Example Workflow   # The name of the workflow

on: [push]  # The event that triggers the workflow

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Welcome message
          run: echo "Hello, world!"


        - name: list files
          run: ls

        - name: read the file
          run: cat README.md

        - name: Generate Ascii artwork
          run: cowsay -f dragon "Run For Cover, I am a Dargon" >> dragon.txt