name: Generate Ascii Artwork

on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Execute the script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh

  second-job:
    needs: first-job    # This ensures second-job runs only after first-job completes
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        run: echo "This job runs after first-job completes"