name: Generate Ascii Artwork # The name of the workflow

on: [push]  # The event that triggers the workflow

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Execute the script
          run: ./ascii-script.sh
       