name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        images: [ hello-world, alpine ]
        exclude:
          - images: alpine
          - os: windoes-latest
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run Images
        run: docker run ${{ matrix.images }}