name: Solar System Workflow

on: 
  workflow_dispatch:

env:
    MONGODB_URI:
    MONGODB_USERNAME:
    MONGODB_PASSWORD:    
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
            matrix : 
                nodejs-version: [ 18 , 19 , 20]
                operating-system: [ ubuntu-latest , macos-latest]
                exclude:
                    - nodejs-version: 18
                      operating-system: macos-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejs-version }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml
        
            