name: Exploring Variables and Secrets

on: [push]

env: 
    IMAGE_NAME: github-actions-nginx
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        
    - name: Docker build
      run: docker build -t docker.io/${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest .    


    - name: Docker push
      run: docker push docker.io/${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME:latest
      
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: docker run -d -p 8080:80 docker.io/${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME:latest
        
        