name: Exploring Variables and Secrets

on: [push]

env: 
    IMAGE_NAME: github-actions-nginx
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - name: Docker login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Docker build
      run: docker build -t docker.io/dockerUsername/imageName:latest .    

    - name: Docker push
      run: docker push docker.io/${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME:latest
      
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: docker run -d -p 8080:80 docker.io/${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME:latest
        
        